#!/bin/sh
set -eu

# Start production server
export BIND="${BIND:-0.0.0.0}"
export PORT="${PORT:-8080}"

# Application binary
APP_BIN="${APP_BIN:-/app/reclamis}"

# Execute application
exec "$APP_BIN"
